// Code generated by MockGen. DO NOT EDIT.
// Source: uploader.go
//
// Generated by this command:
//
//	mockgen --source=uploader.go -destination=mock_uploader.go -package=ossutil
//

// Package ossutil is a generated GoMock package.
package ossutil

import (
	context "context"
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUploader is a mock of Uploader interface.
type MockUploader struct {
	ctrl     *gomock.Controller
	recorder *MockUploaderMockRecorder
	isgomock struct{}
}

// MockUploaderMockRecorder is the mock recorder for MockUploader.
type MockUploaderMockRecorder struct {
	mock *MockUploader
}

// NewMockUploader creates a new mock instance.
func NewMockUploader(ctrl *gomock.Controller) *MockUploader {
	mock := &MockUploader{ctrl: ctrl}
	mock.recorder = &MockUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUploader) EXPECT() *MockUploaderMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockUploader) Put(ctx context.Context, filename string, body io.Reader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, filename, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Put indicates an expected call of Put.
func (mr *MockUploaderMockRecorder) Put(ctx, filename, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockUploader)(nil).Put), ctx, filename, body)
}
