version: "2"
run:
  concurrency: 4
linters:
  settings:
    staticcheck:
      checks:
        - "all"
        - "-QF1010"
        - "-ST1005"
        - "-QF1001"
        - "-QF1008"
        - "-QF1003"
        - "-QF1012"
        - "-ST1000"
        - "-ST1003"
        - "-ST1016"
        - "-ST1020"
        - "-ST1021"
        - "-ST1022"
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - api
      - testdata
      - storage
      - third_party$
      - builtin$
      - examples$
      - web$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
