-- Dump of table cates
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "cates";

CREATE TABLE "cates" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL DEFAULT '',
    "desc" varchar(255) NOT NULL DEFAULT '',
    "domain" varchar(100) NOT NULL DEFAULT '',
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    CONSTRAINT "un_domain" UNIQUE ("domain")
);

-- Dump of table links
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "links";

CREATE TABLE "links" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL DEFAULT '',
    "url" varchar(200) NOT NULL DEFAULT '',
    "desc" varchar(255) NOT NULL DEFAULT '',
    "created_at" TIMESTAMP NOT NULL
);

-- Dump of table moods
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "moods";

CREATE TABLE "moods" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "content" varchar(2048) NOT NULL DEFAULT '',
    "user_id" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL
);

-- Dump of table options
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "options";

CREATE TABLE "options" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "option_key" varchar(100) NOT NULL DEFAULT '',
    "option_value" varchar(2048) NOT NULL DEFAULT '',
    CONSTRAINT "un_option_key" UNIQUE ("option_key")
);

-- Dump of table posts
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "posts";

CREATE TABLE "posts" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "cate_id" INTEGER NOT NULL DEFAULT 1,
    "type" SMALLINT NOT NULL DEFAULT 1,
    "user_id" INTEGER NOT NULL,
    "title" varchar(200) NOT NULL DEFAULT '',
    "url" varchar(100) NOT NULL DEFAULT '',
    "content" TEXT NOT NULL,
    "view_num" INTEGER NOT NULL DEFAULT 1,
    "status" INTEGER NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "posts"."id" IS 'PK';
COMMENT ON COLUMN "posts"."cate_id" IS '文章分类ID';
COMMENT ON COLUMN "posts"."type" IS '1:文章,2:页面';
COMMENT ON COLUMN "posts"."user_id" IS '文章作者ID';
COMMENT ON COLUMN "posts"."title" IS '文章标题';
COMMENT ON COLUMN "posts"."url" IS '页面缩略名';
COMMENT ON COLUMN "posts"."content" IS '文章内容';
COMMENT ON COLUMN "posts"."view_num" IS '浏览次数';
COMMENT ON COLUMN "posts"."status" IS '状态，1正常 2删除 3草稿';
COMMENT ON COLUMN "posts"."created_at" IS '创建时间';
COMMENT ON COLUMN "posts"."updated_at" IS '更新时间';

CREATE INDEX "idx_user" ON "posts" ("user_id");
CREATE INDEX "idx_url" ON "posts" ("url");
CREATE INDEX "idx_created_at" ON "posts" ("created_at");
CREATE INDEX "idx_updated_at" ON "posts" ("updated_at");

-- Dump of table comments
-- ------------------------------------------------------------
DROP TABLE IF EXISTS "comments";

CREATE TABLE "comments" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "post_id" INTEGER NOT NULL,
    "pid" INTEGER NOT NULL,
    "name" varchar(50) NOT NULL DEFAULT '',
    "content" TEXT NOT NULL,
    "ip" varchar(100) NOT NULL DEFAULT '',
    "created_at" TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "comments"."post_id" IS '文章PID';
COMMENT ON COLUMN "comments"."pid" IS '回复评论ID';
COMMENT ON COLUMN "comments"."name" IS '名称';
COMMENT ON COLUMN "comments"."content" IS '内容';
COMMENT ON COLUMN "comments"."ip" IS 'IP';
COMMENT ON COLUMN "comments"."created_at" IS '评论时间';

-- Dump of table users
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "users";

CREATE TABLE "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(100) NOT NULL DEFAULT '用户名',
    "password" varchar(100) NOT NULL DEFAULT '密码',
    "nick_name" varchar(100) NOT NULL DEFAULT '昵称',
    "email" varchar(100) NOT NULL DEFAULT '邮箱',
    "status" SMALLINT NOT NULL DEFAULT 1,
    "type" SMALLINT NOT NULL DEFAULT 1,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    CONSTRAINT "un_user_name" UNIQUE ("name"),
    CONSTRAINT "un_users_email" UNIQUE ("email")
);

COMMENT ON COLUMN "users"."status" IS '1正常，2删除';
COMMENT ON COLUMN "users"."type" IS '1:管理员,2:编辑';

-- Dump of table reminds
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "reminds";

CREATE TABLE "reminds" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" INTEGER NOT NULL,
    "content" varchar(255) NOT NULL DEFAULT '',
    "month" INTEGER NOT NULL,
    "week" INTEGER NOT NULL,
    "day" INTEGER NOT NULL,
    "hour" INTEGER NOT NULL,
    "minute" INTEGER NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "status" INTEGER NOT NULL DEFAULT 1,
    "next_time" TIMESTAMP NOT NULL
);

COMMENT ON COLUMN "reminds"."type" IS '0固定，1每分钟，2每个小时，3每周，4，每天，5，每月，6，每年';
COMMENT ON COLUMN "reminds"."content" IS '内容';
COMMENT ON COLUMN "reminds"."month" IS '月';
COMMENT ON COLUMN "reminds"."week" IS '周';
COMMENT ON COLUMN "reminds"."day" IS '日';
COMMENT ON COLUMN "reminds"."hour" IS '时';
COMMENT ON COLUMN "reminds"."minute" IS '分';
COMMENT ON COLUMN "reminds"."created_at" IS '创建时间';
COMMENT ON COLUMN "reminds"."next_time" IS '下次提醒时间';
